### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by wheatbread** [bocek-wow/SimpleProfessionBroker#1]
Hello!

I received the following error on logging in with SimpleProfessionBroker v0.0.1.  I don't know if it matters, but my professions are Enchanting and Inscription. 

> 10x SimpleProfessionBroker\main.lua:132: attempt to index local 'profession' (a nil value)
> [string "@SimpleProfessionBroker\main.lua"]:132: in function <SimpleProfessionBroker\main.lua:114>
> 
> Locals:
> professionInfo = <table> {
> }
> profession = nil
> (*temporary) = <function> defined @SimpleProfessionBroker\main.lua:64
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index local 'profession' (a nil value)"
> config = <table> {
> }
> GetPlayerProfessions = <function> defined @SimpleProfessionBroker\main.lua:92
> menu = <table> {
>  1 = <table> {
>  }
> }
> BrokerMenuOnClick = <function> defined @SimpleProfessionBroker\main.lua:108
> playerName = "Bast"
> UpdateBroker = <function> defined @SimpleProfessionBroker\main.lua:64
> SetDefaultProfession = <function> defined @SimpleProfessionBroker\main.lua:59
>

**Comment by bocek-wow** [comment]
@wheatbread doesn't look like your character has any professions.  I didn't check that, and should fix it.
